PROJECT_NAME: BE
PROJECT_ID: 
DEPLOYMENT_TARGET: self_hosted

MODE: bff
ACCESS_TOKEN: 
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwdmJrbWxxeG91enpqdGJicnpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzY4MzYsImV4cCI6MjA1OTc1MjgzNn0.wWwvkdBapg1l7Z5aakZ7MxrOpZjdo6jzK5cgXxqynOc
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwdmJrbWxxeG91enpqdGJicnpuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDE3NjgzNiwiZXhwIjoyMDU5NzUyODM2fQ.FJDK20H3ksuKCH4QaOvwa7SmvOtnDJror6GtKrZSCEI

SUPABASE_API_URL: http://localhost:54323
SUPABASE_API_BASE_PATH: /api/pg-meta/default
SUPABASE_API_TOKEN: 2313123213
SUPABASE_API_TOKEN_TYPE: 
SUPABASE_PUBLIC_URL: https://qpvbkmlqxouzzjtbbrzn.supabase.co
SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002
SERVER_DNS: 

ENVIRONMENT: development
VERSION: 1.0.0

ALLOWED_TABLES: '*'
SCHEDULE_STATUS: 'off'

BREAKER_ENABLE: false

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

MAX_SERVER_REQUEST_BODY_SIZE: 8388608

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
